#!/bin/bash

# Move to public files
cd ../squidfingers.github.io

echo "Removing existing files"
find . -path ./.git -prune -o -exec rm -rf {} \; 2> /dev/null

# Move to source files
cd ../squidfingers.github.src

echo "Generating site"
hugo

# Move to public files
cd ../squidfingers.github.io/

echo "Remove category files generated by Projects"
rm -rf categories

echo "Adding files to Git"
git add .
git commit -m "rebuilding site `date`"

echo "Deploying"
git push origin master

# Move to source files
cd ../squidfingers.github.src
echo "Done."
